//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.GRUPO_CLIENTE = new HashSet<GRUPO_CLIENTE>();
            this.MENSAGENS_DESTINOS = new HashSet<MENSAGENS_DESTINOS>();
        }
    
        public int CLIE_CD_ID { get; set; }
        public int PREC_CD_ID { get; set; }
        public int TRF1_CD_ID { get; set; }
        public int VARA_CD_ID { get; set; }
        public Nullable<int> TITU_CD_ID { get; set; }
        public string CLIE_NM_NOME { get; set; }
        public Nullable<decimal> CLIE_VL_VALOR { get; set; }
        public Nullable<decimal> CLIE_VL_VALOR_PAGO { get; set; }
        public string CLIE_NR_OFICIO { get; set; }
        public string CLIE_NR_PROCESSO { get; set; }
        public string CLIE_NM_REU { get; set; }
        public string CLIE_NR_VENCIMENTO { get; set; }
        public Nullable<int> CLIE_IN_PART { get; set; }
        public Nullable<int> CLIE_IN_ATIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRUPO_CLIENTE> GRUPO_CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENSAGENS_DESTINOS> MENSAGENS_DESTINOS { get; set; }
        public virtual TRF TRF { get; set; }
        public virtual PRECATORIO PRECATORIO { get; set; }
        public virtual VARA VARA { get; set; }
        public virtual TITULARIDADE TITULARIDADE { get; set; }
    }
}
