//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTATO
    {
        public int CONT_CD_ID { get; set; }
        public int BENE_CD_ID { get; set; }
        public int QUAL_CD_ID { get; set; }
        public int QUDE_CD_ID { get; set; }
        public Nullable<System.DateTime> CONT_DT_CONTATO { get; set; }
        public string CONT_NM_AGENTE { get; set; }
        public string CONT_NM_REQUERENTE { get; set; }
        public string CONT_NR_TELEFONE { get; set; }
        public string CONT_NR_CPF { get; set; }
        public string CONT_NR_PROTOCOLO { get; set; }
        public Nullable<int> CONT_IN_ATIVO { get; set; }
    
        public virtual PRECATORIO PRECATORIO { get; set; }
        public virtual QUEM_DESLIGOU QUEM_DESLIGOU { get; set; }
        public virtual QUALIFICACAO QUALIFICACAO { get; set; }
    }
}
